### ISSUE TITLE
nil:NilClass errors in config template

### ISSUE THREAD

**Issue by ascendantlogic** [Lispython/sentry-cookbook#14]
When using the methodology prescribed in the README to attempt to bootstrap a server, I'm getting the following error:

```
Chef::Mixin::Template::TemplateError (undefined method `each' for nil:NilClass) on line #84:

 82: SENTRY_REDIS_OPTIONS = {
 83:   "hosts": {
 84:   <% for host, hostsettings in @redis[:hosts] %>
 85:   <%= host %>: {
 86:        <% for key, value in hostsettings %>
```

Noting that it looks like [this line](https://github.com/Lispython/sentry-cookbook/blob/master/definitions/sentry_conf.rb#L70) is what populates the variables, is this something that no longer works in newer versions of Chef?

**Comment by danshultz** [comment]
This is fixed with #15
